CREATE TABLE [dbo].[EximiusParticipantTable] (
    [Id]                    INT            IDENTITY (1, 1) NOT NULL,
    [Email]                 NVARCHAR (50)  NOT NULL,
    [TeamName]              NVARCHAR (MAX) NOT NULL,
    [FullName]              NVARCHAR (MAX) NOT NULL,
    [IGN]                   NVARCHAR (50)  NOT NULL,
    [IC]                    NVARCHAR (50)  NOT NULL,
    [ContactNumber]         NVARCHAR (50)  NOT NULL,
    [Race]                  NVARCHAR (50)  NOT NULL,
    [State]                 NVARCHAR (50)  NOT NULL,
    [Member1_Name]          NVARCHAR (MAX) NOT NULL,
    [Member1_IGN]           NVARCHAR (50)  NOT NULL,
    [Member1_IC]            NVARCHAR (50)  NOT NULL,
    [Member1_ContactNumber] NVARCHAR (50)  NOT NULL,
    [Member1_Race]          NVARCHAR (50)  NOT NULL,
    [Member1_State]         NVARCHAR (50)  NOT NULL,
    [Member2_Name]          NVARCHAR (MAX) NOT NULL,
    [Member2_IGN]           NVARCHAR (50)  NOT NULL,
    [Member2_IC]            NVARCHAR (50)  NOT NULL,
    [Member2_ContactNumber] NVARCHAR (50)  NOT NULL,
    [Member2_Race]          NVARCHAR (50)  NOT NULL,
    [Member2_State]         NVARCHAR (50)  NOT NULL,
    [Member3_Name]          NVARCHAR (MAX) NOT NULL,
    [Member3_IGN]           NVARCHAR (50)  NOT NULL,
    [Member3_IC]            NVARCHAR (50)  NOT NULL,
    [Member3_ContactNumber] NVARCHAR (50)  NOT NULL,
    [Member3_Race]          NVARCHAR (50)  NOT NULL,
    [Member3_State]         NVARCHAR (50)  NOT NULL,
    [Member4_Name]          NVARCHAR (MAX) NOT NULL,
    [Member4_IGN]           NVARCHAR (50)  NOT NULL,
    [Member4_IC]            NVARCHAR (50)  NOT NULL,
    [Member4_ContactNumber] NVARCHAR (50)  NOT NULL,
    [Member4_Race]          NVARCHAR (50)  NOT NULL,
    [Member4_State]         NVARCHAR (50)  NOT NULL,
    [Understand]            BIT            NOT NULL,
    [PhotoPath]             NVARCHAR (MAX) NOT NULL,
    [PhotoPath1]            NVARCHAR (MAX) NULL,
    [PhotoPath2]            NVARCHAR (MAX) NULL,
    [PhotoPath3]            NVARCHAR (MAX) NULL,
    [PhotoPath4]            NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);